### ISSUE TITLE
Not working well with android studio 3.4

### ISSUE THREAD

**Issue by tibi1712** [AdevintaSpain/Protein#36]
In android studio 3.4 is not generating well the code

import io.swagger.annotations.ApiModel
import io.swagger.annotations.ApiModelProperty

@ApiModel
final class ErrorMsg {
  @ApiModelProperty
  @SerializedName("message")
  private var message: String
}

  @GET("/")
  fun WelcomeMsg(): Observable<Comment>

  @GET("/commit")
  fun Commit(): Observable<Comment>

**Comment by ferranpons** [comment]
Hi @tibi1712 

Sorry for replying so late but please could you give me more info about the issue?

An example of json used would be helpful.

Thanks!

**Comment by carlosefonseca** [comment]
I think this is related. I'm trying to install Protein but from the regular plugin repo screen I can only install version 0.3 which does that weird code.
Tried to download and install the plugin from the JetBrains plugin website but Studio 3.5 gives me an "incompatible with this installation" error.

![](https://dsc.cloud/carlosefonseca/Screen-Shot-2019-09-17-11-19-52.86.png)

**Comment by carlosefonseca** [comment]
Updated `def intelliJVersion = 'IC-191.8026.42'` (not sure if relevant) and removed the `untilBuild` from `build.gradle` and I could add it back to Android Studio.

**Comment by ferranpons** [comment]
I've updated the plugin and it should work with the latest version of Android Studio
